---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  externalTrafficPolicy: Local
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      nodePort: 30007
      port: 80
      targetPort: 80
