---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30007
    Name: HTTP
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
